import { parseSceneDefinition, type SceneDefinition } from "./schema";

export interface BuiltInExample {
  id: string;
  category: string;
  summary: string;
  scene: SceneDefinition;
}

const HTTP_CACHE = parseSceneDefinition({
  id: "http-cache",
  title: "Edge cache miss",
  description: "An HTTP request misses at the edge, fills from origin, then returns a cached response.",
  width: 920,
  height: 500,
  durationMs: 5600,
  phases: [
    { id: "request", label: "REQUEST", startMs: 0, snapshotMs: 320 },
    { id: "lookup", label: "LOOKUP", startMs: 800, snapshotMs: 1100 },
    { id: "miss", label: "MISS", startMs: 1500, snapshotMs: 1750 },
    { id: "origin", label: "ORIGIN", startMs: 2200, snapshotMs: 2600 },
    { id: "fill", label: "FILL", startMs: 3300, snapshotMs: 3650 },
    { id: "response", label: "RESPONSE", startMs: 4300, snapshotMs: 4700 },
  ],
  nodes: [
    {
      id: "browser",
      title: "BROWSER",
      subtitle: "GET /diagram.svg",
      x: 38,
      y: 185,
      width: 175,
      height: 90,
      tone: "accent",
      activePhases: ["request", "response"],
    },
    {
      id: "edge",
      title: "EDGE POP",
      eyebrow: "CDN / SFO-03",
      subtitle: "CACHE LOOKUP",
      x: 330,
      y: 145,
      width: 230,
      height: 165,
      tone: "read",
      activePhases: ["lookup", "miss", "fill", "response"],
      states: {
        miss: { subtitle: "MISS / FORWARD", tone: "error" },
        fill: { subtitle: "WRITE CACHE", tone: "data" },
        response: { subtitle: "200 / HIT READY", tone: "commit" },
      },
    },
    {
      id: "cache",
      title: "CACHE SSD",
      subtitle: "OBJECT SLOT",
      x: 365,
      y: 365,
      width: 160,
      height: 82,
      tone: "data",
      activePhases: ["lookup", "fill"],
      states: {
        lookup: { subtitle: "KEY NOT FOUND", tone: "error" },
        fill: { subtitle: "12 KB WRITTEN", tone: "commit" },
      },
    },
    {
      id: "origin",
      title: "ORIGIN",
      eyebrow: "US-WEST-2",
      subtitle: "OBJECT SERVICE",
      x: 710,
      y: 185,
      width: 175,
      height: 90,
      tone: "data",
      activePhases: ["origin", "fill"],
    },
  ],
  edges: [
    {
      id: "browser-edge",
      from: "browser",
      to: "edge",
      tone: "accent",
      activePhases: ["request", "response"],
    },
    {
      id: "edge-origin",
      from: "edge",
      to: "origin",
      tone: "read",
      activePhases: ["miss", "origin", "fill"],
    },
    {
      id: "edge-cache",
      from: "edge",
      to: "cache",
      fromAnchor: "bottom",
      toAnchor: "top",
      tone: "data",
      activePhases: ["lookup", "fill"],
    },
  ],
  transfers: [
    {
      id: "request-packet",
      kind: "packet",
      from: "browser",
      to: "edge",
      label: "GET",
      startMs: 80,
      endMs: 760,
      tone: "accent",
    },
    {
      id: "lookup-packet",
      kind: "packet",
      from: "edge",
      to: "cache",
      fromAnchor: "bottom",
      toAnchor: "top",
      label: "KEY",
      startMs: 820,
      endMs: 1420,
      tone: "read",
    },
    {
      id: "origin-packet",
      kind: "packet",
      from: "edge",
      to: "origin",
      label: "MISS",
      startMs: 1580,
      endMs: 2450,
      tone: "error",
    },
    {
      id: "origin-stream",
      kind: "stream",
      from: "origin",
      to: "edge",
      startMs: 2450,
      endMs: 4100,
      tone: "data",
    },
    {
      id: "fill-stream",
      kind: "stream",
      from: "edge",
      to: "cache",
      fromAnchor: "bottom",
      toAnchor: "top",
      startMs: 3320,
      endMs: 4180,
      tone: "data",
    },
    {
      id: "response-packet",
      kind: "packet",
      from: "edge",
      to: "browser",
      label: "200 OK",
      startMs: 4300,
      endMs: 5350,
      tone: "commit",
    },
  ],
});

const QUEUE_FANOUT = parseSceneDefinition({
  id: "queue-fanout",
  title: "Queue fan-out",
  description: "A broker persists one job, leases it to two workers, and records the final acknowledgement.",
  width: 920,
  height: 520,
  durationMs: 6000,
  phases: [
    { id: "publish", label: "PUBLISH", startMs: 0, snapshotMs: 350 },
    { id: "persist", label: "PERSIST", startMs: 900, snapshotMs: 1250 },
    { id: "dispatch", label: "DISPATCH", startMs: 1800, snapshotMs: 2200 },
    { id: "process", label: "PROCESS", startMs: 3000, snapshotMs: 3400 },
    { id: "ack", label: "ACK", startMs: 4500, snapshotMs: 5000 },
  ],
  nodes: [
    {
      id: "producer",
      title: "PRODUCER",
      subtitle: "JOB #842",
      x: 35,
      y: 205,
      width: 170,
      height: 90,
      tone: "accent",
      activePhases: ["publish"],
    },
    {
      id: "broker",
      title: "BROKER",
      eyebrow: "PARTITION 07",
      subtitle: "READY = 0",
      x: 315,
      y: 175,
      width: 230,
      height: 150,
      tone: "prepare",
      activePhases: ["persist", "dispatch", "ack"],
      states: {
        persist: { subtitle: "READY = 1", tone: "prepare" },
        dispatch: { subtitle: "LEASED = 2", tone: "read" },
        ack: { subtitle: "READY = 0 / ACK", tone: "commit" },
      },
    },
    {
      id: "journal",
      title: "JOURNAL",
      subtitle: "OFFSET 2819",
      x: 350,
      y: 390,
      width: 160,
      height: 82,
      tone: "data",
      activePhases: ["persist", "ack"],
    },
    {
      id: "worker-a",
      title: "WORKER A",
      subtitle: "IDLE",
      x: 710,
      y: 105,
      width: 175,
      height: 90,
      tone: "read",
      activePhases: ["dispatch", "process", "ack"],
      states: {
        process: { subtitle: "RUNNING / 68%", tone: "accent" },
        ack: { subtitle: "DONE", tone: "commit" },
      },
    },
    {
      id: "worker-b",
      title: "WORKER B",
      subtitle: "IDLE",
      x: 710,
      y: 325,
      width: 175,
      height: 90,
      tone: "read",
      activePhases: ["dispatch", "process", "ack"],
      states: {
        process: { subtitle: "RUNNING / 42%", tone: "accent" },
        ack: { subtitle: "DONE", tone: "commit" },
      },
    },
  ],
  edges: [
    {
      id: "producer-broker",
      from: "producer",
      to: "broker",
      tone: "accent",
      activePhases: ["publish"],
    },
    {
      id: "broker-journal",
      from: "broker",
      to: "journal",
      fromAnchor: "bottom",
      toAnchor: "top",
      tone: "data",
      activePhases: ["persist", "ack"],
    },
    {
      id: "broker-worker-a",
      from: "broker",
      to: "worker-a",
      curvature: -0.14,
      tone: "read",
      activePhases: ["dispatch", "ack"],
    },
    {
      id: "broker-worker-b",
      from: "broker",
      to: "worker-b",
      curvature: 0.14,
      tone: "read",
      activePhases: ["dispatch", "ack"],
    },
  ],
  transfers: [
    {
      id: "publish-job",
      kind: "packet",
      from: "producer",
      to: "broker",
      label: "JOB 842",
      startMs: 80,
      endMs: 820,
      tone: "accent",
    },
    {
      id: "persist-job",
      kind: "packet",
      from: "broker",
      to: "journal",
      fromAnchor: "bottom",
      toAnchor: "top",
      label: "APPEND",
      startMs: 920,
      endMs: 1650,
      tone: "data",
    },
    {
      id: "lease-a",
      kind: "packet",
      from: "broker",
      to: "worker-a",
      label: "LEASE A",
      startMs: 1820,
      endMs: 2820,
      curvature: -0.14,
      tone: "read",
    },
    {
      id: "lease-b",
      kind: "packet",
      from: "broker",
      to: "worker-b",
      label: "LEASE B",
      startMs: 2050,
      endMs: 2980,
      curvature: 0.14,
      tone: "read",
    },
    {
      id: "worker-a-ack",
      kind: "packet",
      from: "worker-a",
      to: "broker",
      label: "ACK A",
      startMs: 4550,
      endMs: 5350,
      curvature: 0.14,
      tone: "commit",
    },
    {
      id: "worker-b-ack",
      kind: "packet",
      from: "worker-b",
      to: "broker",
      label: "ACK B",
      startMs: 4750,
      endMs: 5650,
      curvature: -0.14,
      tone: "commit",
    },
  ],
});

const TWO_PHASE_COMMIT = parseSceneDefinition({
  id: "two-phase-commit",
  title: "Two-phase commit",
  description: "A coordinator prepares two shards, collects votes, records the decision, and commits both participants.",
  width: 920,
  height: 520,
  durationMs: 6500,
  phases: [
    { id: "begin", label: "BEGIN", startMs: 0, snapshotMs: 350 },
    { id: "prepare", label: "PREPARE", startMs: 900, snapshotMs: 1300 },
    { id: "vote", label: "VOTE", startMs: 2200, snapshotMs: 2600 },
    { id: "log", label: "LOG", startMs: 3400, snapshotMs: 3750 },
    { id: "commit", label: "COMMIT", startMs: 4300, snapshotMs: 4800 },
    { id: "ack", label: "ACK", startMs: 5600, snapshotMs: 6000 },
  ],
  nodes: [
    {
      id: "client",
      title: "CLIENT",
      subtitle: "TRANSFER $42",
      x: 35,
      y: 205,
      width: 170,
      height: 90,
      tone: "accent",
      activePhases: ["begin", "ack"],
    },
    {
      id: "coordinator",
      title: "COORDINATOR",
      eyebrow: "TXN 9F2A",
      subtitle: "OPEN",
      x: 305,
      y: 175,
      width: 240,
      height: 150,
      tone: "prepare",
      activePhases: ["prepare", "vote", "log", "commit", "ack"],
      states: {
        vote: { subtitle: "VOTES 2 / 2", tone: "read" },
        log: { subtitle: "DECISION DURABLE", tone: "data" },
        commit: { subtitle: "COMMITTING", tone: "commit" },
        ack: { subtitle: "COMPLETE", tone: "commit" },
      },
    },
    {
      id: "decision-log",
      title: "TXN LOG",
      subtitle: "NO DECISION",
      x: 345,
      y: 390,
      width: 160,
      height: 82,
      tone: "data",
      activePhases: ["log", "commit"],
      states: {
        log: { subtitle: "COMMIT / FSYNC", tone: "data" },
        commit: { subtitle: "COMMIT DURABLE", tone: "commit" },
      },
    },
    {
      id: "shard-a",
      title: "SHARD A",
      subtitle: "UNLOCKED",
      x: 710,
      y: 105,
      width: 175,
      height: 90,
      tone: "lock",
      activePhases: ["prepare", "vote", "commit", "ack"],
      states: {
        prepare: { subtitle: "PREPARED / LOCKED", tone: "lock" },
        vote: { subtitle: "YES", tone: "read" },
        commit: { subtitle: "COMMITTED", tone: "commit" },
        ack: { subtitle: "UNLOCKED", tone: "commit" },
      },
    },
    {
      id: "shard-b",
      title: "SHARD B",
      subtitle: "UNLOCKED",
      x: 710,
      y: 325,
      width: 175,
      height: 90,
      tone: "lock",
      activePhases: ["prepare", "vote", "commit", "ack"],
      states: {
        prepare: { subtitle: "PREPARED / LOCKED", tone: "lock" },
        vote: { subtitle: "YES", tone: "read" },
        commit: { subtitle: "COMMITTED", tone: "commit" },
        ack: { subtitle: "UNLOCKED", tone: "commit" },
      },
    },
  ],
  edges: [
    {
      id: "client-coordinator",
      from: "client",
      to: "coordinator",
      tone: "accent",
      activePhases: ["begin", "ack"],
    },
    {
      id: "coordinator-log",
      from: "coordinator",
      to: "decision-log",
      fromAnchor: "bottom",
      toAnchor: "top",
      tone: "data",
      activePhases: ["log"],
    },
    {
      id: "coordinator-a",
      from: "coordinator",
      to: "shard-a",
      curvature: -0.14,
      tone: "lock",
      activePhases: ["prepare", "vote", "commit"],
    },
    {
      id: "coordinator-b",
      from: "coordinator",
      to: "shard-b",
      curvature: 0.14,
      tone: "lock",
      activePhases: ["prepare", "vote", "commit"],
    },
  ],
  transfers: [
    {
      id: "begin-txn",
      kind: "packet",
      from: "client",
      to: "coordinator",
      label: "BEGIN",
      startMs: 80,
      endMs: 820,
      tone: "accent",
    },
    {
      id: "prepare-a",
      kind: "packet",
      from: "coordinator",
      to: "shard-a",
      label: "PREPARE",
      startMs: 920,
      endMs: 1950,
      curvature: -0.14,
      tone: "lock",
    },
    {
      id: "prepare-b",
      kind: "packet",
      from: "coordinator",
      to: "shard-b",
      label: "PREPARE",
      startMs: 1120,
      endMs: 2100,
      curvature: 0.14,
      tone: "lock",
    },
    {
      id: "vote-a",
      kind: "packet",
      from: "shard-a",
      to: "coordinator",
      label: "YES",
      startMs: 2220,
      endMs: 3150,
      curvature: 0.14,
      tone: "read",
    },
    {
      id: "vote-b",
      kind: "packet",
      from: "shard-b",
      to: "coordinator",
      label: "YES",
      startMs: 2400,
      endMs: 3250,
      curvature: -0.14,
      tone: "read",
    },
    {
      id: "log-decision",
      kind: "packet",
      from: "coordinator",
      to: "decision-log",
      fromAnchor: "bottom",
      toAnchor: "top",
      label: "FSYNC",
      startMs: 3420,
      endMs: 4200,
      tone: "data",
    },
    {
      id: "commit-a",
      kind: "packet",
      from: "coordinator",
      to: "shard-a",
      label: "COMMIT",
      startMs: 4320,
      endMs: 5450,
      curvature: -0.14,
      tone: "commit",
    },
    {
      id: "commit-b",
      kind: "packet",
      from: "coordinator",
      to: "shard-b",
      label: "COMMIT",
      startMs: 4520,
      endMs: 5550,
      curvature: 0.14,
      tone: "commit",
    },
    {
      id: "final-ack",
      kind: "packet",
      from: "coordinator",
      to: "client",
      label: "OK",
      startMs: 5620,
      endMs: 6350,
      tone: "commit",
    },
  ],
});

export const BUILT_IN_EXAMPLES: readonly BuiltInExample[] = [
  {
    id: HTTP_CACHE.id,
    category: "NETWORK",
    summary: "Cache lookup, origin fetch, fill, and response.",
    scene: HTTP_CACHE,
  },
  {
    id: QUEUE_FANOUT.id,
    category: "MESSAGING",
    summary: "Persisted delivery, parallel workers, and acknowledgements.",
    scene: QUEUE_FANOUT,
  },
  {
    id: TWO_PHASE_COMMIT.id,
    category: "DATABASE",
    summary: "Prepare, vote, durable decision, and commit.",
    scene: TWO_PHASE_COMMIT,
  },
] as const;

export function resolveBuiltInExample(id: string | null | undefined): BuiltInExample {
  return BUILT_IN_EXAMPLES.find((example) => example.id === id) ?? BUILT_IN_EXAMPLES[0]!;
}
